version: '3'

services:
  db_service:
    container_name: db_contanainer
    restart: always
    image: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - ./data_db:/var/lib/postgresql/data
  api_service:
    container_name: api_container
    image: api
    depends_on:
      - db_service
    command: bash -c "yarn start"
    build: ./
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - '3333:3333'
